### ISSUE TITLE
Bug in regards to "cannot fetch certificate: no endpoints available for service "http:sealed-secrets-controller:"

### ISSUE THREAD

**Issue by ghostsquad** [bitnami-labs/sealed-secrets#502]
This is after reading #317 #397 and #368 all slightly related.

## Description

Error message:

```
cannot fetch certificate: no endpoints available for service "http:sealed-secrets-controller:
```

## Repro Steps

if my `sealed-secrets-controller` `service` is configured with:

```
spec:
  clusterIP: 172.20.54.13
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
```

it does NOT work

but if you remove the port name `http` it works fine, i.e.

```
spec:
  clusterIP: 172.20.54.13
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
```

### Testing

shell 1
```
kubectl proxy
```

shell2
```
curl http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/http:sealed-secrets-controller:/proxy/v1/cert.pem
```

## Other Related Information

I use the bitnami kube.libsonnet libraries to manage my deployments & services, only using upstream yamls as reference (not truth), and `Service()` function does this automatically!

```
Service(name): $._Object("v1", "Service", name) {
    local service = self,

    target_pod:: error "service target_pod required",
    port:: self.target_pod.spec.containers[0].ports[0].containerPort,

    // Helpers that format host:port in various ways
    host:: "%s.%s.svc" % [self.metadata.name, self.metadata.namespace],
    host_colon_port:: "%s:%s" % [self.host, self.spec.ports[0].port],
    http_url:: "http://%s/" % self.host_colon_port,
    proxy_urlpath:: "/api/v1/proxy/namespaces/%s/services/%s/" % [
      self.metadata.namespace,
      self.metadata.name,
    ],
    // Useful in Ingress rules
    name_port:: {
      serviceName: service.metadata.name,
      servicePort: service.spec.ports[0].port,
    },

    spec: {
      selector: service.target_pod.metadata.labels,
      ports: [
        {
          port: service.port,
          name: service.target_pod.spec.containers[0].ports[0].name,
          targetPort: service.target_pod.spec.containers[0].ports[0].containerPort,
        },
      ],
      type: "ClusterIP",
    },
  },
```
  
https://github.com/bitnami-labs/kube-libsonnet/blob/master/kube.libsonnet#L181
  
---
  
The curl call can be resolved by appending the port name:
```
curl http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/http:sealed-secrets-controller:http/proxy/v1/cert.pem
```
  
```diff
- http:sealed-secrets-controller:
+ http:sealed-secrets-controller:http
```

### `kube.libsonnet` workaround

```
local k = import 'kubernetes/kube.libsonnet';

{
  local addon = $.sealedSecrets,
  local config = $.config_.sealedSecrets,

  sealedSecrets+: {
    service+: k.Service(config.name, config.namespace) {
      local service = self,

      target_pod:: addon.deployment.spec.template,
      spec+: {
        ports: [
          // this port must be unnamed until this issue is resolved
          // https://github.com/bitnami-labs/sealed-secrets/issues/502
          {
            port: service.port,            
            targetPort: service.target_pod.spec.containers[0].ports[0].containerPort,
          },
        ],
      },
    },
  },
}
```

Note: `lib/` is in my jsonnet path (I'm using Tanka), and so `kubernetes/kube.libsonnet` actually refers to a local file `lib/kubernetes/kube.libsonnet` which _wraps_ the upstream bitnami-labs kube.libsonnet. Just adding this note in case anyone is confused why the function here takes 2 arguments (name & namespace) where the upstream requires only 1 argument.

**Comment by haimari** [comment]
In my case same Helm chart: [bitnami-labs](https://bitnami-labs.github.io/sealed-secrets)
works fine on Rancher RKE on prem clusters and not on cloud.

Same Helm, with same values (deployed as HelmRelease via Flux)

In the the `sealed-secrets-controller` `svc` there is **no port name** by default. 
Tried to add/remove & change it manually by editing the `svc` which didn't help.

In the `Helm values` (of the working on prem clusters) I set the values:

```yaml
  values:
    fullnameOverride: sealed-secrets-controller
```

but with and without this `value` it fails in cloud (civo + Digital Ocean) with error:

when running `kubeseal` command:

```bash
kubeseal -o yaml < civo-secret.yaml >  civo-sealed-secret.yaml
```

```
error: cannot fetch certificate: error trying to reach service: dial tcp 10.42.0.7:8080: i/o timeout
```

Again, exact same Helm works On prem

### Helm values:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      version: "1.16.1"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  interval: 10m
  values:
    fullnameOverride: sealed-secrets-controller
    commandArgs:
      - "--update-status"
    crd:
      # crd.create: `true` if the crd resources should be created
      create: true
      # crd.keep: `true` if the sealed secret CRD should be kept when the chart is deleted
      keep: true
```

### Service

```bash
kubectl get svc/sealed-secrets-controller -n kube-system -o yaml
```

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: sealed-secrets
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2021-11-01T13:48:16Z"
  labels:
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/version: v0.16.0
    helm.sh/chart: sealed-secrets-1.16.1
    helm.toolkit.fluxcd.io/name: sealed-secrets
    helm.toolkit.fluxcd.io/namespace: kube-system
  name: sealed-secrets-controller
  namespace: kube-system
  resourceVersion: "22220"
  uid: c5158d18-16be-4394-9204-ff4e0cf9adaa
spec:
  clusterIP: 10.43.225.37
  clusterIPs:
  - 10.43.225.37
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: sealed-secrets
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by nagyv** [comment]
I run into the same issue as described by @haimari. I try to use sealed secrets on a civo cluster, and I could not rule out that being the culprit.

### How to reproduce

1. Install sealed secrets from yaml, version `0.16.0`
2. Run `kubeseal -v 10 --fetch-cert > sealed-secrets.pub.pem`

### Current behaviour

```bash
kubeseal -v 10 --fetch-cert > sealed-secrets.pub.pem
I1206 15:43:08.285667   72953 loader.go:375] Config loaded from file:  /Users/nagyviktor/.kube/config
I1206 15:43:08.286336   72953 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/x-pem-file, */*" -H "User-Agent: kubeseal/v0.0.0 (darwin/amd64) kubernetes/$Format" 'https://ip.removed:6443/api/v1/namespaces/kube-system/services/http:sealed-secrets-controller:/proxy/v1/cert.pem'
I1206 15:43:38.421849   72953 round_trippers.go:443] GET https://ip.removed:6443/api/v1/namespaces/kube-system/services/http:sealed-secrets-controller:/proxy/v1/cert.pem 500 Internal Server Error in 30134 milliseconds
I1206 15:43:38.421882   72953 round_trippers.go:449] Response Headers:
I1206 15:43:38.421890   72953 round_trippers.go:452]     Cache-Control: no-cache, private
I1206 15:43:38.421897   72953 round_trippers.go:452]     Content-Type: application/json
I1206 15:43:38.421902   72953 round_trippers.go:452]     Date: Mon, 06 Dec 2021 14:43:38 GMT
I1206 15:43:38.421908   72953 round_trippers.go:452]     Content-Length: 160
I1206 15:43:38.421987   72953 request.go:968] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"error trying to reach service: dial tcp 10.42.2.5:8080: i/o timeout","code":500}
error: cannot fetch certificate: error trying to reach service: dial tcp 10.42.2.5:8080: i/o timeout
```

The controller logs are:

```
 controller version: v0.16.0                                                                                                                                                                                                                                
 2021/12/06 14:42:53 Starting sealed-secrets controller version: v0.16.0                                                                                                                                                                                    
 2021/12/06 14:42:53 Searching for existing private keys                                                                                                                                                                                                    
 2021/12/06 14:42:53 ----- sealed-secrets-keyqrlhq                                                                                                                                                                                                          
 2021/12/06 14:42:53 HTTP server serving on :8080
```

### Expected behaviour

The public key is created locally, without errors.

**Comment by razielgn** [comment]
Also getting this with the new `2.0.1` chart.

**Comment by nagyv** [comment]
Are you on civo.com or with a different Kubernetes service?

Federico Ravasio ***@***.***> ezt írta (időpont: 2021. dec.
16., Csü 19:01):

**Comment by razielgn** [comment]
> Are you on civo.com or with a different Kubernetes service?

Sorry, forgot to mention. AWS EKS 1.21.5.

**Comment by rajeshsingh624** [comment]
I verified that the issue exist in version: v0.17.1

**Comment by philipp1992** [comment]
can reproduce, when i remove the "Http" name from the service, it works

**Comment by alphabet5** [comment]
I ran into the same issue following the [fluxcd docs](https://fluxcd.io/docs/guides/sealed-secrets/) and the proxy/curl examples here did not work. This is what worked for me.

Terminal 1
```bash
kubectl proxy
```

Terminal 2
```bash
curl http://127.0.0.1:8001/api/v1/namespaces/flux-system/services/sealed-secrets-controller:8080/proxy/v1/cert.pem
```

Removing http: from the beginning of sealed-secrets-controller, and appending :8080 to specify the port.

**Comment by seansabour** [comment]
I'm also running into this issue via helm install and noticed it was fixed in another helm repo, but was not ported over to this repo: https://github.com/helm/charts/pull/22097

**Comment by robert197** [comment]
I encountered this error after upgrading the helm chart to 2.0.1 the helm chart version 1.16.1 works fine.

https://artifacthub.io/packages/helm/bitnami-labs/sealed-secrets

Downgraded again and now everything works fine again.

**Comment by khdevel** [comment]
The change in the `service.yaml` provided in the commit [7fcd9f3](https://github.com/bitnami-labs/sealed-secrets/commit/7fcd9f3669feda32994c1116897c25e438b83871) is the reason of the problem when we use [v2.0.1](https://github.com/bitnami-labs/sealed-secrets/blob/helm-v2.0.1/helm/sealed-secrets/templates/service.yaml) of the Helm Chart. In [v2.0.0](https://github.com/bitnami-labs/sealed-secrets/blob/helm-v2.0.0/helm/sealed-secrets/templates/service.yaml) there is no such problem.

**Comment by exocode** [comment]
@nagyv 
I am running on Civo... Is there a known issue? I tried current (latest) Helm chart as well latest controller: https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.1/controller.yaml


```
❯ kubeseal -v 10 --fetch-cert > sealed-secrets.pub.pem
I1222 12:08:58.759834    8036 loader.go:375] Config loaded from file:  /Users/jan/.kube/config
I1222 12:08:58.764416    8036 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/x-pem-file, */*" -H "User-Agent: kubeseal/v0.0.0 (darwin/amd64) kubernetes/$Format" 'https://xx.xx.xx.xx:6443/api/v1/namespaces/kube-system/services/http:sealed-secrets-controller:/proxy/v1/cert.pem'
I1222 12:08:58.967174    8036 round_trippers.go:443] GET https://xx.xx.xx.xx:6443/api/v1/namespaces/kube-system/services/http:sealed-secrets-controller:/proxy/v1/cert.pem 404 Not Found in 202 milliseconds
I1222 12:08:58.967195    8036 round_trippers.go:449] Response Headers:
I1222 12:08:58.967200    8036 round_trippers.go:452]     Content-Type: application/json
I1222 12:08:58.967204    8036 round_trippers.go:452]     Date: Wed, 22 Dec 2021 11:08:59 GMT
I1222 12:08:58.967208    8036 round_trippers.go:452]     Content-Length: 226
I1222 12:08:58.967211    8036 round_trippers.go:452]     Cache-Control: no-cache, private
I1222 12:08:58.967258    8036 request.go:1017] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services \"sealed-secrets-controller\" not found","reason":"NotFound","details":{"name":"sealed-secrets-controller","kind":"services"},"code":404}
error: cannot fetch certificate: services "sealed-secrets-controller" not found
```

Controller logs: 
```
controller version: 0.17.1
2021/12/22 11:03:39 Starting sealed-secrets controller version: 0.17.1
2021/12/22 11:03:39 Searching for existing private keys
2021/12/22 11:03:42 New key written to default/sealed-secrets-keyjgd6s
2021/12/22 11:03:42 Certificate is 
-----BEGIN CERTIFICATE-----
MIIEzTCCArWgAwIBAgIRAJSgHJ9slB+V4iO3IVAyO5MwDQYJKoZIhvcNAQELBQAw
....
...
..
.
hEjTNrU/xLCts4mVC39NJaAoSxg84BFVz3A8U8gFC9aWVIGVTE5mjE5mBOh7nxDa
```

**Comment by tchen** [comment]
Also getting this bug with Chart 2.0.2, on AWS EKS.

    $ kubeseal --fetch-cert --controller-name=sealed-secrets --controller-namespace=default < mysecret.json
    error: cannot fetch certificate: no endpoints available for service "http:sealed-secrets:"

    $ helm list
    NAME            NAMESPACE       REVISION        UPDATED                                 STATUS     CHART                    APP VERSION
    sealed-secrets  default         1               2021-12-24 06:44:31.578450624 +0000 UTC deployed   sealed-secrets-2.0.2     v0.17.1

    $ kubeseal --version
    kubeseal version: 0.17.1

    $ kubectl version
    Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:52:11Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by juan131** [comment]
Hi everyone! 

Thanks so much for reporting this! The changes we recently introduced at https://github.com/bitnami-labs/sealed-secrets/pull/690 (introducing a name for the http port exposed in the service) broke the compatibility with kubeseal.

This should be fixed by this PR: https://github.com/bitnami-labs/sealed-secrets/pull/648

In the meantime, you can workaround this by removing the `name` and setting `targetPort: 8080` as @glitchcrab pointed out at https://github.com/bitnami-labs/sealed-secrets/issues/694#issuecomment-997370679.

**Comment by juan131** [comment]
Hi everyone! I’m glad to announce that we just released a new version of Sealed Secrets that address this issue: `v0.17.2`
Please give it a try when you have a chance! Find more info at:
- https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.17.2
- https://github.com/bitnami-labs/sealed-secrets/blob/main/RELEASE-NOTES.md

**Comment by davidkarlsen** [comment]
@juan131 great news - thanks! Will the brew package be updated soon too?

**Comment by juan131** [comment]
That should be automatically done in a few hours @davidkarlsen 

There's a bot (https://github.com/BrewTestBot) that usually does the magic for us updating this homebrew formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubeseal.rb

**Comment by Mirdrack** [comment]
Im still getting the error using the helm chart `2.1.0` and the app version `v0.17.2`
I already update the helm repo, upgrade the chart and reinstalled the chart.
```
NAME          	NAMESPACE     	REVISION	UPDATED                             	STATUS  	CHART               	APP VERSION
sealed-secrets	sealed-secrets	1       	2022-01-17 13:25:01.643849 -0600 CST	deployed	sealed-secrets-2.1.0	v0.17.2
```


The specs of my service still has http as target port:
```
spec:
  clusterIP: 10.0.38.145
  clusterIPs:
  - 10.0.38.145
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
```
Is there anything else I'm missing?
Thank you!

**Comment by sathieu** [comment]
@Mirdrack This works for me, with chart 2.1.0 and app v0.17.2:

```console
kubeseal --controller-namespace=sealed-secrets           --controller-name=sealed-secrets --fetch-cert
```

> The specs of my service still has http as target port

This is expected.

Have you updated kubeseal?

```
$ kubeseal --version
kubeseal version: 0.17.2
```

**Comment by rufreakde** [comment]
@sathieu 

I have the following setup:

```
#ArgoCD Application helm chart 2.1.0 no custom parameters
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.1.0
    helm:
      releaseName: sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeseal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
```
and the following kubeseal version:
```
kubeseal --version
kubeseal version: v0.17.2
```
Agent Service:
```
apiVersion: v1
kind: Service
metadata:
...
  labels:
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/version: v0.17.2
    helm.sh/chart: sealed-secrets-2.1.0
  name: sealed-secrets
  namespace: kubeseal
...
spec:
  clusterIP: 100.68.140.219
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/name: sealed-secrets
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

But when I try to seal a secret I get the following:
```
# --controller-name=sealed-secrets --controller-namespace=kubeseal
error: cannot fetch certificate: error trying to reach service: read tcp 192.168.123.6:43798->100.96.1.29:8080: read: connection reset by peer
```

I dont understand what the issue is here?

**Comment by rufreakde** [comment]
Okay when we use kube-system as the default namespace the issue seems to be fixed!
```
# argocd
...
    helm:
      releaseName: sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeseal
...
```

**Comment by juan131** [comment]
Hi @rufreakde 

> Okay when we use kube-system as the default namespace the issue seems to be fixed

Well.. It should work regardless the namespace you're using to deploy the SealedSecrets controller. As far as you set correctly the namespace and service name (passed through `--controller-namespace` and `--controller-namespace` flags) when executing **kubeseal**, everything should work.

**Comment by jorgebirck** [comment]
I still have the issue, I have to go and edit the service inside Kubernetes to make it work. I'm using the updated brew version.

**Comment by CapKenR** [comment]
I just installed kubeseal following the fluxcd documentation.
```
flux create source helm sealed-secrets --interval=1h --url=https://bitnami-labs.github.io/sealed-secrets
flux create helmrelease sealed-secrets --interval=1h --release-name=sealed-secrets-controller --target-namespace=flux-system --source=HelmRepository/sealed-secrets --chart=sealed-secrets --chart-version=">=1.15.0-0" --crds=CreateReplace
```
This used the 2.6.0 version of the chart and 0.18.1 of the application.

I also just installed version 0.18.1 of the kubeseal CLI.

I'm still getting the timeout error.

```
$ kubeseal --fetch-cert --controller-name=sealed-secrets-controller --controller-namespace=flux-system
error: cannot fetch certificate: error trying to reach service: dial tcp 100.96.1.94:8080: i/o timeout
```

I can port forward the service and retrieve the certificate.
